### ISSUE TITLE
variable 'nodeData' referenced before assignment

### ISSUE THREAD

**Issue by mlasala** [jasonmcintosh/rabbitmq-nagios-plugins#2]
The check_rabbit_server.py script shows this error msg:
UNKNOWN: Error occurred:local variable 'nodeData' referenced before assignment

**Comment by fdask** [comment]
Getting the same error.

**Comment by jasonmcintosh** [comment]
Sorry I've not updated this thing in a LONG while.  Feel free to fork and investigate and submit a pull request.  I've moved away from Nagios to zabbix for all my monitoring at this point.

**Comment by Tr4sK** [comment]
Put the FQDN in your hostname parameter.

/etc/rabbitmq/rabbitmq-env.conf
RABBITMQ_USE_LONGNAME=true

**Comment by bogdanstoica35** [comment]
Since our checks are against a production server running RabbitMQ, we have used a different approach (which requires no rabbitmq service restart):

**hosts.conf file** 
```
object Host "your-host" {
  check_command = "hostalive"
  address = "ip-address"
  display_name = "fqdn-of-the-hostname"
..
}
```

**then services.conf**

/* RabbitMQ */
```
apply Service "rabbitmq-check-server" {
  import "generic-service"
  ..
  vars.rmq_host = host.display_name (by default I was using host.address which resulted in the above mentioned error
 ..
  }
```
